import { getDefaultConfig } from '@rainbow-me/rainbowkit';

export const rainbowKitTheme = {
  colors: {
    accentColor: '#4ade80',
    accentColorForeground: '#000000',
    actionButtonBorder: '#374151',
    actionButtonBorderMobile: '#374151',
    actionButtonSecondaryBackground: '#1f2937',
    closeButton: '#9ca3af',
    closeButtonBackground: '#2b2e4a',
    connectButtonBackground: '#2b2e4a',
    connectButtonBackgroundError: '#ef4444',
    connectButtonInnerBackground: '#1f2937',
    connectButtonText: '#ffffff',
    connectButtonTextError: '#ffffff',
    connectionIndicator: '#4ade80',
    downloadBottomCardBackground: '#1f2937',
    downloadTopCardBackground: '#374151',
    error: '#ef4444',
    generalBorder: '#374151',
    generalBorderDim: '#1f2937',
    menuItemBackground: '#2b2e4a',
    modalBackdrop: 'rgba(0, 0, 0, 0.5)',
    modalBackground: '#1f2937',
    modalBorder: '#374151',
    modalText: '#ffffff',
    modalTextDim: '#9ca3af',
    modalTextSecondary: '#d1d5db',
    profileAction: '#2b2e4a',
    profileActionHover: '#374151',
    profileForeground: '#1f2937',
    selectedOptionBorder: '#4ade80',
    standby: '#f59e0b',
  },
  fonts: {
    body: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  radii: {
    actionButton: '8px',
    connectButton: '8px',
    menuButton: '8px',
    modal: '12px',
    modalMobile: '12px',
  },
  shadows: {
    connectButton: '0px 4px 12px rgba(0, 0, 0, 0.1)',
    dialog: '0px 8px 32px rgba(0, 0, 0, 0.32)',
    profileDetailsAction: '0px 2px 4px rgba(0, 0, 0, 0.1)',
    selectedOption: '0px 2px 4px rgba(0, 0, 0, 0.1)',
    selectedWallet: '0px 2px 4px rgba(0, 0, 0, 0.1)',
    walletLogo: '0px 2px 4px rgba(0, 0, 0, 0.1)',
  },
  blurs: {
    modalOverlay: 'blur(8px)',
  },
}; 